/**
 * Web-only UI chrome strings (placeholders, buttons, boot screens).
 *
 * Why not core i18n keys: the core dictionaries serve the TUI's slash
 * command + message domain; web chrome (Send button, input placeholder,
 * boot error page) has no counterpart there. Resolved per-render via
 * ``getActiveLang()`` so a future runtime language switch just works.
 */
import { getActiveLang } from "@blade-ai/core";

const DICT = {
  en: {
    inputPlaceholder: "Describe a fault to inject, or type / for commands…",
    send: "Send",
    stop: "Stop",
    stopHint: "Esc to interrupt",
    connecting: "Connecting to the backend…",
    bootFailedTitle: "Cannot reach the backend",
    bootFailedHint:
      "This page is served by `blade-ai web`. If you opened it from a dev server, start the backend first.",
    streamStateLabel: "state",
    exitHint:
      "The browser host can't close this tab for you — close the tab to end the session.",
    paletteKbdLabel: "Command palette",
    palettePlaceholder: "Type a command…",
    paletteEmpty: "No matching commands",
    paletteHint: "↑↓ select · Enter fill into input · Esc close",
    navChat: "Chat",
    navTasks: "Tasks",
    railNavLabel: "Primary navigation",
    tasksTitle: "Tasks",
    tasksFilterAll: "All",
    tasksFilterActive: "Active",
    tasksFilterFailed: "Failed",
    tasksColStatus: "Status",
    tasksColFault: "Fault",
    tasksColPhase: "Phase",
    tasksColDuration: "Duration",
    tasksColTokens: "Tokens",
    tasksColCreated: "Created",
    tasksEmpty: "No tasks yet — start a drill from the chat.",
    tasksEmptyFilter: "Nothing matches this filter.",
    tasksLoading: "Loading tasks…",
    tasksLoadFailed: "Failed to load tasks",
    sessionsTitle: "Sessions",
    sessionNew: "New session",
    sessionNewFailed: "Failed to create session",
    sessionDelete: "Delete session",
    sessionsLoadFailed: "Failed to load sessions",
    // — Session panel (design §6 会话历史面板): time-grouped session
    // list beside the chat column. Entry titles are built ONLY from
    // fields the sessions endpoint actually returns (task_count +
    // created_at) — never invent a name the wire doesn't carry.
    sessionGroupToday: "Today",
    sessionGroupYesterday: "Yesterday",
    sessionGroupWeek: "Past 7 days",
    sessionGroupEarlier: "Earlier",
    // — Empty-conversation hero (mock v2 scene 1): greeting + sub +
    // starter chips shown while the session has no history yet.
    heroGreetingMorning: "Good morning — time to forge a drill",
    heroGreetingAfternoon: "Good afternoon — time to forge a drill",
    heroGreetingEvening: "Good evening — time to forge a drill",
    heroSub:
      "Describe the fault to inject; I handle execution, verification and recovery safely.",
    heroChipCpu: "Inject CPU full load on payment-service",
    heroChipNetwork: "Simulate gateway network latency",
    heroChipRecent: "How did the latest drill go?",
    heroChipWhat: "What faults can I inject?",
    sessionTasksNone: "No tasks",
    sessionDotLive: "Drill in progress",
    sessionDotDone: "Drill finished",
    sessionDotFail: "Drill failed",
    sessionTasksOne: "1 task",
    sessionTasksMany: "{n} tasks",
    sessionMore: "Session actions",
    sessionDeleteArm: "Click again to confirm",
    sessionDeleteBlocked: "Active drill in this session",
    sessionSwitchFailed: "Failed to switch session",
    sessionDeleteFailed: "Failed to delete session",
    sessionPanelCollapse: "Collapse sessions",
    sessionPanelExpand: "Expand sessions",
    taskDetailLoading: "Loading task…",
    taskDetailLoadFailed: "Failed to load task",
    taskDetailTarget: "target",
    taskDetailPhase: "phase",
    taskDetailWindow: "window",
    taskDetailModel: "model",
    taskDetailCost: "cost",
    taskDetailExperimentUid: "experiment uid",
    taskDetailVerification: "Verification",
    taskDetailWarnings: "warning(s)",
    taskDetailSpans: "Node spans",
    taskDetailSpansNone: "(none recorded)",
    taskDetailError: "Error",
    taskDetailUseCase: "use case",
    taskDetailIntent: "intent",
    taskDetailPlanned: "planned",
    taskDetailTimeline: "Timeline",
    taskDetailTimelineNone: "(no timeline in the postmortem)",
    taskDetailChecklist: "Checklist",
    taskDetailRecoverVerification: "Recovery verification",
    taskDetailPostmortem: "Postmortem",
    taskDetailFullReport: "Full report",
    taskDetailFeasibility: "Feasibility",
    // — Trace page (/trace): the per-task process audit view.
    navTrace: "Trace",
    traceListTitle: "Tasks",
    traceEmpty: "No tasks yet — start a drill from the chat.",
    traceSelectHint: "Select a task to inspect its execution trace.",
    traceSummaryNodes: "nodes",
    traceSummaryTools: "tools",
    traceSummaryConfirm: "confirm gate",
    navCharts: "Charts",
    chartsTitle: "Drill charts",
    chartsTimeline: "Phase timeline",
    chartsTimelineHint:
      "Per-task stacked phase durations — prepare / inject / verify / recover — newest first.",
    chartsUsage: "Token usage by model",
    chartsUsageHint: "Aggregated token usage by model across the same tasks.",
    chartsLoading: "Loading charts…",
    chartsEmpty: "No tasks with metrics yet — charts land once a drill runs.",
    chartsLoadFailed: "Failed to load charts",
    chartsPhasePrep: "Prepare",
    chartsPhaseInject: "Inject",
    chartsPhaseVerify: "Verify",
    chartsPhaseRecover: "Recover",
    chartsTokensIn: "Input",
    chartsTokensOut: "Output",
    chartsModelUnknown: "(unknown model)",
    navSettings: "Settings",
    settingsTitle: "Settings",
    settingsHint:
      "Each row writes on change; cold keys are marked until the next restart.",
    settingsLoading: "Loading settings…",
    settingsLoadFailed: "Failed to load settings",
    settingsGroupModel: "Model",
    settingsModelCustom: "Custom…",
    settingsModelApply: "Apply",
    settingsGroupGeneration: "Generation",
    settingsGroupBehavior: "Behavior",
    settingsGroupCluster: "Cluster",
    settingsGroupAdvanced: "Advanced",
    settingsSubTimeouts: "Timeouts",
    settingsSubLoops: "Loop caps",
    settingsSubReplan: "Replan",
    settingsSubDetection: "Loop detection",
    settingsLanguage: "Language",
    settingsLangBrowser: "Browser",
    settingsCredentials: "Credentials",
    settingsCredentialsHint:
      "Managed by the CLI wizard (`blade-ai` then /config) — shown masked here, never editable in the browser.",
    settingsNotSet: "(not set)",
    settingsConfigPath: "config file",
    settingsRestart: "restart required",
    // — DAG panel (design §7.2): right-rail execution graph. Node names
    // render verbatim; these captions carry the business semantics.
    dagPanelTitle: "Execution graph",
    dagEmptyHint: "Nodes light up as the agent works through a turn.",
    dagLoopBadge: "round-trips through its screener/tools sub-loop",
    dagReplanLabel: "verify-replan back-edge to the agent loop",
    dagGroupPostmortem: "Postmortem",
    timelinePanelTitle: "Progress timeline",
    timelineEmptyHint: "Node progress lands here as the run unfolds.",
    // — Right progress rail (design §7.2 + mock col-4): live drill
    // summary → countdown → phases → params → safety → timeline.
    // The whole rail renders only while a drill is live.
    railTitle: "Current drill",
    railLive: "LIVE",
    railCountdown: "Auto-recovery countdown",
    railDurationAuto: "auto-recovery at deadline",
    railPhaseTitle: "Phases",
    railParamsTitle: "Injection parameters",
    railSafetyTitle: "Safety checks",
    railCopy: "Copy command",
    railCopied: "Copied",
    railApproved: "approved",
    railViewDag: "View execution graph",
    railViewDagHint: "LangGraph node detail",
    railCollapse: "Collapse panel",
    railExpand: "Expand panel",
    dagOverlayClose: "Close panel",
    dagCapIntentClarification: "Intent clarification",
    dagCapPlanBuilder: "Plan building",
    dagCapIntentConfirm: "Intent confirmation",
    dagCapSafetyCheck: "Safety whitelist check",
    dagCapConfirmationGate: "Human confirmation gate",
    dagCapPreplanProbe: "Pre-plan probe",
    dagCapBatchSetup: "Batch setup",
    dagCapAgentLoop: "Plan & tool calls",
    dagCapBaselineCapture: "Baseline capture",
    dagCapSeSnapshot: "Side-effect snapshot",
    dagCapExecuteLoop: "Fault execution",
    dagCapVerifierLoop: "Verification rounds",
    dagCapFinalizeVerification: "Finalize verification",
    dagCapSeDetect: "Side-effect diff",
    dagCapTerminalReports: "Reports & archiving",
    dagCapRecoverVerifierLoop: "Recovery verification",
    dagCapFinalizeRecoverVerification: "Finalize recovery",
    // — Info cards: web-side labels that differ from the TUI's.
    // ``tuiVersion`` carries the CLIENT's build version; rendering it
    // under the TUI's "tui version" label would misname the host.
    doctorClientVersion: "client version",
  },
  zh: {
    inputPlaceholder: "描述要注入的故障,或输入 / 查看命令…",
    send: "发送",
    stop: "终止",
    stopHint: "Esc 中断",
    connecting: "正在连接后端…",
    bootFailedTitle: "无法连接后端",
    bootFailedHint: "本页面由 blade-ai web 托管。若你从 dev server 打开,请先启动后端。",
    streamStateLabel: "状态",
    exitHint: "浏览器宿主无法代你关闭标签页——关闭本标签页即结束会话。",
    paletteKbdLabel: "命令面板",
    palettePlaceholder: "输入命令搜索…",
    paletteEmpty: "无匹配命令",
    paletteHint: "↑↓ 选择 · Enter 填入输入框 · Esc 关闭",
    navChat: "对话",
    navTasks: "任务",
    railNavLabel: "主导航",
    tasksTitle: "任务",
    tasksFilterAll: "全部",
    tasksFilterActive: "进行中",
    tasksFilterFailed: "失败",
    tasksColStatus: "状态",
    tasksColFault: "故障",
    tasksColPhase: "阶段",
    tasksColDuration: "时长",
    tasksColTokens: "Tokens",
    tasksColCreated: "创建时间",
    tasksEmpty: "暂无任务——在对话中发起一次演练。",
    tasksEmptyFilter: "该筛选下没有任务。",
    tasksLoading: "正在加载任务…",
    tasksLoadFailed: "任务加载失败",
    sessionsTitle: "会话",
    sessionNew: "新建会话",
    sessionNewFailed: "新建会话失败",
    sessionDelete: "删除会话",
    sessionsLoadFailed: "会话列表加载失败",
    // — 会话面板（设计 §6 会话历史面板）：对话列旁的时间分组会话列表。
    // 条目标题只由会话端点真实返回的字段构成（task_count +
    // created_at）——不臆造线上不存在的名称。
    sessionGroupToday: "今天",
    sessionGroupYesterday: "昨天",
    sessionGroupWeek: "过去 7 天",
    sessionGroupEarlier: "更早",
    // — 空会话 hero（mock v2 场景 1）：问候 + 副标题 + 起步 chips，
    // 会话尚无历史时展示。
    heroGreetingMorning: "早上好，来锻造一次演练",
    heroGreetingAfternoon: "下午好，来锻造一次演练",
    heroGreetingEvening: "晚上好，来锻造一次演练",
    heroSub: "描述要注入的故障，我负责安全地执行、验证与恢复",
    heroChipCpu: "给 payment-service 注入 CPU 满载",
    heroChipNetwork: "模拟网关网络延迟",
    heroChipRecent: "最近的演练怎么样",
    heroChipWhat: "我能注入哪些故障？",
    sessionTasksNone: "暂无任务",
    sessionDotLive: "演练进行中",
    sessionDotDone: "演练已完成",
    sessionDotFail: "演练失败",
    sessionTasksOne: "1 个任务",
    sessionTasksMany: "{n} 个任务",
    sessionMore: "会话操作",
    sessionDeleteArm: "再次点击确认删除",
    sessionDeleteBlocked: "该会话存在进行中的演练",
    sessionSwitchFailed: "会话切换失败",
    sessionDeleteFailed: "会话删除失败",
    sessionPanelCollapse: "收起会话栏",
    sessionPanelExpand: "展开会话栏",
    taskDetailLoading: "正在加载任务…",
    taskDetailLoadFailed: "任务加载失败",
    taskDetailTarget: "目标",
    taskDetailPhase: "阶段",
    taskDetailWindow: "时间窗",
    taskDetailModel: "模型",
    taskDetailCost: "开销",
    taskDetailExperimentUid: "experiment uid",
    taskDetailVerification: "验证",
    taskDetailWarnings: "条警告",
    taskDetailSpans: "节点时间线",
    taskDetailSpansNone: "(无记录)",
    taskDetailError: "错误",
    taskDetailUseCase: "用例",
    taskDetailIntent: "意图",
    taskDetailPlanned: "计划时长",
    taskDetailTimeline: "执行时间线",
    taskDetailTimelineNone: "（复盘报告未生成时间线）",
    taskDetailChecklist: "验证清单",
    taskDetailRecoverVerification: "恢复验证",
    taskDetailPostmortem: "复盘摘要",
    taskDetailFullReport: "完整报告",
    taskDetailFeasibility: "可行性",
    // — 过程页（/trace）：单任务执行过程审计视图。
    navTrace: "过程",
    traceListTitle: "任务",
    traceEmpty: "暂无任务——在对话中发起一次演练。",
    traceSelectHint: "选择一个任务查看其执行过程。",
    traceSummaryNodes: "节点",
    traceSummaryTools: "工具",
    traceSummaryConfirm: "人工确认",
    navCharts: "图表",
    chartsTitle: "演练图表",
    chartsTimeline: "阶段时间线",
    chartsTimelineHint: "每任务按 准备/注入/验证/恢复 堆叠的耗时，最新在前。",
    chartsUsage: "按模型的 Token 用量",
    chartsUsageHint: "同一批任务按模型聚合的 Token 用量。",
    chartsLoading: "正在加载图表…",
    chartsEmpty: "暂无可图表化的任务——演练执行后自动生成。",
    chartsLoadFailed: "图表加载失败",
    chartsPhasePrep: "准备",
    chartsPhaseInject: "注入",
    chartsPhaseVerify: "验证",
    chartsPhaseRecover: "恢复",
    chartsTokensIn: "输入",
    chartsTokensOut: "输出",
    chartsModelUnknown: "(未知模型)",
    navSettings: "设置",
    settingsTitle: "设置",
    settingsHint: "每行修改即写入；冷启动键会标记为待重启后生效。",
    settingsLoading: "正在加载设置…",
    settingsLoadFailed: "设置加载失败",
    settingsGroupModel: "模型",
    settingsModelCustom: "自定义…",
    settingsModelApply: "应用",
    settingsGroupGeneration: "生成",
    settingsGroupBehavior: "行为",
    settingsGroupCluster: "集群",
    settingsGroupAdvanced: "高级",
    settingsSubTimeouts: "超时",
    settingsSubLoops: "循环上限",
    settingsSubReplan: "重规划",
    settingsSubDetection: "循环检测",
    settingsLanguage: "界面语言",
    settingsLangBrowser: "跟随浏览器",
    settingsCredentials: "凭据",
    settingsCredentialsHint:
      "由 CLI 向导管理（blade-ai 后输入 /config）——此处仅掩码展示，浏览器内不可编辑。",
    settingsNotSet: "(未设置)",
    settingsConfigPath: "配置文件",
    settingsRestart: "需重启生效",
    // — DAG 面板（设计 §7.2）：右栏执行图。节点名原样渲染，业务语义由副标题承载。
    dagPanelTitle: "执行图",
    dagEmptyHint: "随 Agent 处理一轮对话，节点逐一点亮。",
    dagLoopBadge: "经 screener/工具子循环往返",
    dagReplanLabel: "验证重规划回边，返回 Agent 循环",
    dagGroupPostmortem: "收尾",
    timelinePanelTitle: "进展时间线",
    timelineEmptyHint: "节点进展随执行流入此处。",
    // — 右进展区（设计 §7.2 + mock 第四列）：概要 → 倒计时 → 阶段 →
    // 参数 → 安全检查 → 时间线。仅演练进行中整栏渲染。
    railTitle: "当前演练",
    railLive: "LIVE",
    railCountdown: "自动恢复倒计时",
    railDurationAuto: "到时自动恢复",
    railPhaseTitle: "演练阶段",
    railParamsTitle: "注入参数",
    railSafetyTitle: "安全检查",
    railCopy: "复制命令",
    railCopied: "已复制",
    railApproved: "批准注入",
    railViewDag: "查看执行图",
    railViewDagHint: "LangGraph 节点详情",
    railCollapse: "收起面板",
    railExpand: "展开面板",
    dagOverlayClose: "关闭面板",
    dagCapIntentClarification: "意图澄清",
    dagCapPlanBuilder: "计划构建",
    dagCapIntentConfirm: "意图确认",
    dagCapSafetyCheck: "安全白名单校验",
    dagCapConfirmationGate: "人工确认门禁",
    dagCapPreplanProbe: "预规划探测",
    dagCapBatchSetup: "批量准备",
    dagCapAgentLoop: "规划与工具调用",
    dagCapBaselineCapture: "基线采集",
    dagCapSeSnapshot: "副作用快照",
    dagCapExecuteLoop: "故障执行",
    dagCapVerifierLoop: "验证轮次",
    dagCapFinalizeVerification: "验证定稿",
    dagCapSeDetect: "副作用比对",
    dagCapTerminalReports: "报告与归档",
    dagCapRecoverVerifierLoop: "恢复验证",
    dagCapFinalizeRecoverVerification: "恢复定稿",
    // — 信息卡：web 端与 TUI 不同的标签。``tuiVersion`` 字段承载的是
    // 客户端构建版本，沿用 TUI 的 "tui version" 标签会误名宿主。
    doctorClientVersion: "客户端版本",
  },
} as const;

type UiText = Record<keyof (typeof DICT)["en"], string>;

export function ui(): UiText {
  return DICT[getActiveLang()] ?? DICT.en;
}
